### ISSUE TITLE
Integration with Slick

### ISSUE THREAD

**Issue by rubenfiszel** [sangria-graphql/sangria-relay-playground#4]
Hello, 

I tried to add slick-play and slick-play-evoloutions to this repo:

```
  "com.typesafe.play" %% "play-slick" % "2.0.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "2.0.0",
```

 but I get this error each time:

```
java.lang.NoSuchMethodError: play.api.Logger$.init(Ljava/io/File;Lscala/Enumeration$Value;)V
    at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:88)
    at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:61)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:60)
    at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
    at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at play.runsupport.Reloader$.startDevMode(Reloader.scala:223)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
```

I tried to add slf4j dependencies but it doesn't work.

My intuition is that there is a conflict between the play already inside one of the dependency and slick-play.  What is the best way to integrate sangria-relay with slick-play ?

**Comment by yasserkaddour** [comment]
Hi, thanks for your interest,

Yes the project was previously on play 2.4 and you should have used "play-slick" % "1.1.1" according their [readme](https://github.com/playframework/play-slick#all-releases), I just migrated the project to play 2.5, I tested it now with "play-slick" % "2.0.0" and everything seems to work. 

Tell me if you run with any issue.

**Comment by rubenfiszel** [comment]
it's fixed now. Thanks. I'm actually building a startup centered on a fintech webapplication. I will use sangria relay for our backend as it seems to fit our need. Would you advise against it ? The pros are that it enable us to integrate financial calculations directly in Scala in the backend and use relay.

**Comment by yasserkaddour** [comment]
If your team is already familiar with Scala and your are decided to use Relay then Sangria is great. The question is do your application need to fetch frequently data from a graph complex enough, to justify the use of Relay ? Relay was build by Facebook for their special needs. If you think your application will be big enough then go with Relay otherwise a simple API will do.

I myself is building a social network Startup and my need definitively justify Relay.

**Comment by OlegIlyenko** [comment]
Sounds like a good fit to me. GraphQL also makes it easier to expose additional convenience functionality via parametrized fields. In myself worked in this area (order fulfillment backed services, which includes payments and a lot of financial calculations) and must admit that JVM and Scala are very good for this kind of applications. Sangria also has build-in support for `BigDecimal` and `BigInt` which you may find useful (depending in how you model monetary amounts). Just be sure not to use `Double`s :D

**Comment by rubenfiszel** [comment]
I actually don't think I "need" relay per se. But I feel like it's the
future of API and that there is no drawbacks to use it. The data model is
actually not really a graph and I might not need to fetch that often but I
also feel like it adds a bit of structure. I'm gonna use react as the
frontend and I felt like relay + graphql were fitting well with it. I might
be wrong.

2016-03-17 20:04 GMT+01:00 Oleg Ilyenko notifications@github.com:

**Comment by yasserkaddour** [comment]
The lack of users and learning resource compared to the well established redux is a drawback, but if your team is competent it won't be an issue.

**Comment by rubenfiszel** [comment]
I wish I had a team. I'm the CEO and sole developpers for now. My co-founders are doing the mathematical models. I'm actually looking for competent developpers for react, relay or sangria. It's a bit overwhelming to do everything :D

**Comment by yasserkaddour** [comment]
Yeah very overwhelming, I am kinda in the same situation. I will recommend you to read [Hello Startup](http://www.hello-startup.net/) by Yevgeniy Brikman, it's a programmer perspective on building a Startup, I found it extremely helpful. 

 I wish you all the best
